.github/actions/setup-addon/action.yml
requirements/dev.txt

Tests were crashing in GHAs with this message:
```
running the test CRASHED with signal 6
```
See https://github.com/AnkiHubSoftware/ankihub_addon/actions/runs/10273257966/job/28427314731?pr=996
This PR fixes the problem by specifying version of these libraries in `dev.txt`:
```
pyqt5==5.15.5
pyqtwebengine==5.15.6
```
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-567

[BUILD-567] fix: Test crashing in GHA

---

ankihub/entry_point.py
ankihub/gui/js_message_handling.py
ankihub/gui/reviewer.py
ankihub/settings.py
tests/addon/test_integration.py

In the card preview add a **Copy Note ID** button when shown on the AnkiHub Webapp and a **Open in browser** button when shown on Anki Desktop.
This is the addon-side of the task. This is the web app PR: https://github.com/AnkiHubSoftware/ankihub/pull/2260
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-575
- Add `is_on_anki=True` query argument to flashcard selector url in `settings.py`
- ref: Move js/pycmd message handling code from `reviewer.py` to `js_message_handling.py`
- The reason is that the `OPEN_BROWSER_PYCMD` is now used for the flashcard selector as well, and not just in the reviewer. So it's better to move it to a separate module. Other pycmd code which could also be useful in multiple contexts was also moved to …

[BUILD-575] feat: Show open-in-browser button in card preview of flashcard selector

---

ankihub/gui/webview.py

When you open the flashcard selector and the token is not (longer) valid, the flashcard selector should close and the login dialog should open. 
However, currently this doesn't happen and this window stays open: 
This PR fixes this.
- Move the `_handle_auth_failure_if_needed` call

[BUILD-589] fix: Handle auth failure in flashcard selector

---

ankihub/gui/webview.py

On MacOs, the flashcard selector dialog was sometimes hiding behind the main Anki window. This task fixes this.
Addresses this QA feedback: https://ankihub.atlassian.net/browse/BUILD-477?focusedCommentId=11355
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-593
- Raise and activate the flashcard selector dialog when its parent window (main Anki dialog) gets activated.
- I tried other solutions, but this is tricky to solve on MacOs (see e.g. https://bugreports.qt.io/browse/QTBUG-56829) and this solution works well enough according to QA feedback.

[BUILD-593] feat: Tweak flashcard selector to not hide behind parent window

---

ankihub/gui/messages/templates/deck_import_summary.html

This fixes unnecessary white space on the **deck import summary** dialog.
The problem is occurring when installing multiple decks at once.
**Before**
**After**
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-594
- Move line breaks to other places in the jinja template

[BUILD-594] fix: Whitespace on deck import summary dialog

---

ankihub/gui/overview.py

When you click on the AnKing deck on the main Anki window, if the deck is installed, but the destination Anki deck does not exist, an `NotFoundError` error is shown.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-610
https://ankihub.sentry.io/issues/5787476509/?project=6546414&referrer=github-pr-bot
- Check if the destination deck exists in Anki before calling `aqt.mw.col.decks.deck_and_child_ids`

[BUILD-610] fix: Error when opening deck overview when AnKing destination deck does not exist

---

.github/workflows/ci.yml
ankihub/gui/js_message_handling.py
ankihub/gui/web/ankihub_ai.js
ankihub/gui/web/post_message_to_ankihub_js.js
ankihub/gui/webview.py
ankihub/settings.py
tests/addon/test_integration.py

Getting note suspension states from Anki when on an AnkiHub web page is currently only available from the AnkiHub AI chatbot iframe. This task makes it also available from the flashcard selector webview.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-621
- Post the note suspension states response message...
- to the chatbot iframe if it exists in the context
- to the current window otherwise
- Make `ANKING_DECK_ID` configurable using env var
- Bump GHA upload-artifact and download-artifact to version 4 because the previous version got deprecated
See the how-to-reproduce-section here: https://github.com/AnkiHubSoftware/ankihub/pull/2312

[BUILD-621] chore: Make get_note_suspension_states available from flashcard selector

---

ankihub/gui/web/ankihub_ai.js

For the chatbot AI, we should update the icon as we did on the flashcard selector.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-625
- Change icon
- Add tooltip
- Open Anki
- Start a review session for the AnKing deck
- The AnkiHub AI icon should be there
- If it's not there, make sure that the `chatbot` feature flag is active
- Also make sure that the `ANKING_DECK_ID` env var for the add-on is set to the deck id of the deck

[BUILD-625] feat: Change ankihub AI icon and add tooltip

---

.github/workflows/upload_to_ankiweb.yml

This fixes the upload-to-ankiweb GHA by bumping `webdriver_manager` to v4.0.2.
Currently, the GHA fails: https://github.com/AnkiHubSoftware/ankihub_addon/actions/runs/11105034314/job/30850355014
I reproduced this locally.
Installing `webdriver_manager==4.0.2` fixed it.
Also see https://github.com/SergeyPirogov/webdriver_manager/issues/670#issuecomment-2264755178
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-673

[BUILD-673] chore: Fix upload-to-ankiweb GHA

---

ankihub/entry_point.py
ankihub/gui/deck_updater.py
ankihub/gui/overview.py
ankihub/gui/reviewer.py
ankihub/gui/suggestion_dialog.py
ankihub/private_config_migrations.py
ankihub/settings.py
tests/addon/conftest.py
tests/addon/test_integration.py

Currently, when the "use_staging" setting is changed, this does not affect the `ANKING_DECK_ID` setting.
This causes some problems when "use_staging" is set to `true''. For example, the AnkiHub AI features do not show up for the AnKing deck on staging.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-683
https://theanking.slack.com/archives/C01E9EJ1W2E/p1727791389645969?thread_ts=1727713744.955879&cid=C01E9EJ1W2E
- Move the `ANKING_DECK_ID` setting to the config
- Use the id of the AnKing deck on staging when "use_staging" is set to `true`

[BUILD-683] chore: Use correct anking deck id for staging

---

ankihub/ankihub_client/models.py
ankihub/gui/overview.py
ankihub/gui/reviewer.py
ankihub/gui/utils.py
ankihub/gui/webview.py
ankihub/settings.py
tests/addon/test_integration.py
tests/factories.py
tests/fixtures.py

- [BUILD-692](https://ankihub.atlassian.net/browse/BUILD-692)
- [BUILD-694](https://ankihub.atlassian.net/browse/BUILD-694)
This PR updates the addon making sure that buttons of the "smart search" and the "chatbot" are available for other decks that have note embeddings.
[BUILD-692]: https://ankihub.atlassian.net/browse/BUILD-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BUILD-694]: https://ankihub.atlassian.net/browse/BUILD-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-692] [BUILD-694] chore: Enable smart search and ai chatbot for other decks

---

ankihub/gui/js_message_handling.py

This is necessary for the complete functionality of the chatbot changes introduced in:
- https://github.com/AnkiHubSoftware/ankihub/pull/2370
This PR adds a new conditional branch that handles the `ankihub_copy_to_clipboard` that will be sent by the chatbot iframe when the "copy link" button is clicked (see related PR).
This is because using the `navigator.clipboard.writeText(data)` inside an iframe is not allowed by default, and setting `allow="clipboard-write *"` (and inumerous other variants of this) didn't yield the desired result. Maybe this is a bug related to the specific browser that anki uses.
If you want to try your luck out there, It's dangerous to go alone, take [this](https://web.dev/articles/async-clipboard#permissions-policy-integration) and …

add handler for copy to clipboard pycmd JS-sent event

---

ankihub/gui/reviewer.py
ankihub/gui/web/ankihub_ai.js

We want to show the chatbot icon on AnkiHub notes which were not suggested/accepted yet.
Currently, we only show it for notes which are accepted and have an AnkiHub note id.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-720
- Show the chatbot icon in the reviewer for all notes that have an AnkiHub id, note type or are in an AnkiHub deck

[BUILD-720] chore: Show chatbot for notes with AnkiHub note id, note type or deck

---

ankihub/db/db.py
tests/addon/test_unit.py

Currently, when reviewing a note with a non-AnkiHub note type, this error occurs:
```
File "ankihub/gui/reviewer.py", line 126, in _add_ankihub_ai_js_to_reviewer_web_content
ah_dids = {ah_did_of_note, ah_did_of_deck, *ah_dids_of_note_type} - {None}
TypeError: 'NoneType' object is not iterable
```
The reason is that the `ankihub_dids_for_note_type` function can return `None`.
To fix this, we can make it return an empty set instead of `None` when there are no AnkiHub deck ids for the note type.
- Return an empty set from the `ankihub_dids_for_note_type` function if there are no results instead of `None`
- Update test

[BUILD-725] fix: TypeError in reviewer

---

.github/actions/setup-addon/action.yml
ankihub/ankihub_client/ankihub_client.py
requirements/dev.txt

Currently we are clearing the token before the signout-request, which leads to the signout-request not being authorized.
- Clear token after signout request.

fix: Clear token after logout request, not before

---

ankihub/ankihub_client/ankihub_client.py
ankihub/db/__init__.py
ankihub/db/db.py
ankihub/gui/browser/browser.py
ankihub/gui/browser/custom_search_nodes.py
ankihub/gui/operations/db_check/ah_db_check.py
ankihub/gui/operations/db_check/anki_db_check.py
ankihub/main/reset_local_changes.py
ankihub/main/subdecks.py
tests/addon/performance/test_ankihub_importer.py
tests/addon/test_integration.py
tests/addon/test_unit.py

We are currently not filtering out deleted notes in some DB queries where they should be filtered out.
This leads to issues such as the one reported here: https://community.ankihub.net/t/i-am-not-able-to-reset-the-local-changes-made-to-tha-anki-hub-deck/323705/16 
This task fixes this.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-741
Community report: https://community.ankihub.net/t/i-am-not-able-to-reset-the-local-changes-made-to-tha-anki-hub-deck/323705/18
Sentry: https://ankihub.sentry.io/issues/5592235372/?project=6546414&query=id%3A88e49e2126f14c1eb809372a9b4cae4f&referrer=issue-stream&statsPeriod=90d&stream_index=0.
- [Speed up resetting local changes, skip deleted notes](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1020/commits/8 …

[BUILD-741] fix: Filter out deleted notes in db queries, speed up resetting local changes

---

ankihub/ankihub_client/ankihub_client.py
ankihub/ankihub_client/models.py
ankihub/main/review_data.py
tests/addon/test_unit.py
tests/client/cassettes/TestSendDailyCardReviewSummaries.test_basic.yaml
tests/client/test_client.py

Create a new method on the addon to access the new endpoint created to store the daily summary of the review stats.
https://ankihub.atlassian.net/browse/BUILD-746
- Rename `DailyCardReviewSummaryData` to DailyCardReviewSummary`
- [ref: Rename DailyCardReviewSummary](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1023/commits/0fca729533d09bbcf0b1fadf8bd8f33b3df7fa16)
- It's the same name as the model on the web app
- Add `send_daily_card_review_summaries` method to `AnkiHubClient`
- Add test

[BUILD-746] Create client method for storing review data

---

ankihub/db/db.py

The filtering of the notes to upsert takes a very long time when there are many notes to filter out. 
I tested with 30k notes and it took more than a minute.
With this change it takes a couple of seconds at most.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-762
- Use set instead of list when filtering notes to upsert into AnkiHub DB

[BUILD-762] perf: Use set when filtering notes to upsert into AnkiHub DB

---

ankihub/feature_flags.py
ankihub/gui/operations/ankihub_sync.py
ankihub/gui/overview.py
ankihub/gui/reviewer.py
ankihub/main/review_data.py
ankihub/settings.py
tests/addon/conftest.py
tests/addon/test_unit.py
tests/fixtures.py

- [BUILD-748](https://ankihub.atlassian.net/browse/BUILD-748)
This PR makes these changes:
* Add the function `send_daily_review_summaries` which will send to the AnkiHub server the compiled data of the daily reviews
* Call this function in the background after the user sync
* Update the `feature_flags.py` module and its use to avoid the need to update the dataclass if a new feature flag is created on the server
1. Run the instance of the ankihub server and make sure that the feature flag `daily_card_review_summary` is enabled
2. Open a deck and review a card
3. Open the anki database and update the ID of the newly created `revlog` row to the value of a timestamp of yesterday's date
4.  Click on the "Sync with AnkiHub" option on the Ankihub menu
5. Go to a shell instance of the Ankihub …

 [BUILD-748] feat: Add function to send the daily summary review data after the sync

---

ankihub/gui/operations/ankihub_sync.py
ankihub/main/review_data.py
ankihub/settings.py
tests/addon/test_integration.py
tests/addon/test_unit.py

Currently there is an issue with sending daily review summaries:
Example scenario:
Day 1: User reviews cards on mobile, then syncs with AnkiWeb
Day 2: User launches Anki Desktop, and automatically syncs with AnkiHub and AnkiWeb.
The issue is that on day 2, things happen in this order:
- AnkiHub sync, which among other things, sends the review data from Day 1 to the web app
- AnkiWeb sync, which adds the reviews done on mobile on Day 1 to Anki's database
So, the reviews done on mobile on day 1 will be missing from our data on the web app.
- Only send review data from x days ago.
- For example, if a user syncs every day, we would send the summary for `date.today() - timedelta(days=x)`  every day
- We can assume that the further in the past the reviews were done, the higher the chance that …

Send daily review summaries with delay to wait for reviews from other devices to be synced

---

ankihub/gui/errors.py
tests/addon/test_unit.py

Related web app PR: https://github.com/AnkiHubSoftware/ankihub/pull/2411
> We changed the API version and this requires users to update the addon.
When this happens, the add-on should show a message that it need to be update.
However, it shows an error message instead.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-773
Sentry: https://ankihub.sentry.io/issues/5458237219/?project=6546414&query=is%3Aunresolved%20406&referrer=issue-stream&statsPeriod=7d&stream_index=0
Discourse: https://community.ankihub.net/t/406-error-master-thread/335342
We were expecting this to be true for the response (on the client-side): 
```python
response.reason="Outdated client, please update the AnkiHub add-on."
```
This works locally, but when communicating with the …

[BUILD-773] fix: Show update-addon dialog when api version not supported

---

ankihub/gui/errors.py
tests/addon/test_unit.py

Currently, when the add-on has no internet connection, and you try to do an action which requires communication with AnkiHub, you get an error message instead of the no-connection message.
This task fixes this.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-816
- Check type of `exc_value` instead of type of `exc_value.original_exception` in `_try_handle_exception`
- The `exc_value` is now unwrapped here:
https://github.com/AnkiHubSoftware/ankihub_addon/blob/758cea7b3e5995e97cc3c1565fc869adbfc35c1f/ankihub/gui/errors.py#L245-L246
- Check if internet connection is available using socket, instead of based on the connection error message
- Before this change I was getting the "AnkiHub is undergoing routine maintenance" message even if I didn't have …

[BUILD-816] fix: Handle connection errors

---

ankihub/main/review_data.py
pyproject.toml
tests/addon/conftest.py
tests/addon/test_integration.py
tests/fixtures.py

When processing revlog entries to create daily review summaries, we should be excluding revlog entries with `revlog_type==anki.consts.REVLOG_RESCHED`. These entries are created when an user reschedules the reviews of cards and do not represent real reviews.
This leads to review summaries such as [this](https://app.ankihub.net/careless-chimp-oasis/users/dailycardreviewsummary/15/change/) one, where the "total cards studied" does not equal the sum of "total cards marked again", "total cards marked good", etc.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-817
- Exclude reschedules from review data
- Add tests
- chore: [Ignore mypy errors in media_import and media_export](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1034/commits/de5c2b6c20d8 …

[BUILD-817] fix: Exclude reschedules from review data

---

ankihub/gui/reviewer.py
ankihub/gui/web/mh_integration_tabs.html
ankihub/gui/webview.py

- [BUILD-834](https://ankihub.atlassian.net/browse/BUILD-834)
This PR adds a new provisional button to trigger the split-screen functionality, which opens a dedicated WebView instance to display content from user-specified URLs.
1. Go to the ankihub and create and enable the feature flag "mh_integration"
2. On Anki click on the option -> AnkiHub -> Sync with AnkiHub
3. Go to the card review page
4. Click on the button "Toggle Split Screen"
5. This should open a webview
6. Click on one of the tabs to change the website
[BUILD-834]: https://ankihub.atlassian.net/browse/BUILD-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-834] feat: Add split screen to the card review

---

ankihub/gui/web/mh_no_urls_empty_state.html

- [BUILD-869](https://ankihub.atlassian.net/browse/BUILD-869)
This PR makes these changes:
* Update the empty state page
1. Pass an empty `url_list` to `SplitScreenWebViewManager`
2. Click on one of the buttons "Boards & beyond" or "First Aid Forward"
[BUILD-869]: https://ankihub.atlassian.net/browse/BUILD-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-869] feat: Update empty state view with new messaging and icons

---

ankihub/gui/reviewer.py
ankihub/gui/web/ankihub_ai.js
ankihub/gui/web/reviewer_buttons.js
ankihub/gui/web/sidebar_tabs.html

This task makes the following adjustments to the reviewer UI:
- Adjusts chatbot position to not overlap with the reviewer buttons according to the [design on Figma](https://www.figma.com/design/rWzQ7PPqAXf1piz5yTntaT/%F0%9F%91%91--Ankihub?node-id=7722-55966&t=gM6naxDA47rE3UkS-1)
- Set a minimum width for the sidebar and the main Anki window when the sidebar is open
- Remove arrow buttons from the sidebar header
- Make the close button in the sidebar header work
- Remove expand button as per the discussion here: https://www.figma.com/design/rWzQ7PPqAXf1piz5yTntaT?node-id=7721-53457#1051310302
- Adjust sidebar header styling
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-886
https://github.com/user-attachments/assets/5cddc30d-a9c4-4ec6-8135-1aa3bba5 …

[BUILD-886] feat: Adjust sidebar and chatbot UI

---

ankihub/gui/js_message_handling.py
ankihub/gui/reviewer.py
ankihub/gui/web/mh_no_urls_empty_state.html
ankihub/gui/web/sidebar_tabs.html
ankihub/main/utils.py
ankihub/settings.py
tests/addon/test_unit.py

We need to set the tabs in the sidebar based on the B&B and FA4 tags of the reviewed card.
The tabs should be updated when the sidebar is opened and when the reviewed card changes. 
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-890
- `js_message_handling.py`: Set up message handler for `OPEN_LINK_PYCMD`, which will be sent by the web app in order to open pages in an external browser if needed (for example for Boards and Beyond)
- The command gets introduced into the web app in this PR: https://github.com/AnkiHubSoftware/ankihub/pull/2458
- `reviewer.py`: 
- Update the tabs based on B&B and FA tags when the sidebar is opened
- Handle auth failures in the sidebar when accessing the preview pages
- The auth failure is handled by closing the sidebar …

[BUILD-890] feat: Populate sidebar tabs based on mh tags

---

ankihub/gui/reviewer.py
ankihub/gui/web/reviewer_buttons.js

https://ankihub.atlassian.net/browse/BUILD-897
This PR hides the B&B and FA buttons side panel buttons for non-AnKing decks.
1. Go to the AnKing deck and confirm the buttons are still displayed.
2. Go to a different deck and confirm the buttons are not displayed.
In the AnKing deck:
In other decks:

[BUILD-897] Show B&B and FA buttons for the AnKing deck only

---

ankihub/gui/web/reviewer_buttons.js
ankihub/gui/web/sidebar_tabs.html

- [BUILD-918](https://ankihub.atlassian.net/browse/BUILD-918)
This PR adds a toggle button that will hide the sidebar buttons.
1. Go to the card review
2. Click on the button with the right arrow to collapse the buttons
3. Click again to show the buttons
[Screencast from 2024-12-17 10-11-12.webm](https://github.com/user-attachments/assets/c826f4db-1013-4337-accf-63c141c830e7)
[BUILD-918]: https://ankihub.atlassian.net/browse/BUILD-918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-918] feat:  Add toggle element to sidebar buttons

---

ankihub/main/utils.py
tests/addon/test_unit.py

The `mh_tag_to_resource_title_and_slug` function doesn't work correctly for some tags.
In particular, it doesn't ignore some parts of the tag which should be ignored.
It should ignore trailing `::Extra` tag parts, for example for this tag:
`#AK_Step1_v12::#B&B::03_Biochem::03_Amino_Acids::04_Ammonia::Extra`
the slug should be this:
`step1-bb-biochem-amino_acids-ammonia`
(The `::Extra` part indicates that the tag is a secondary tag for the resource referenced by it.)
It should also ignore all tag parts starting with a tag part that begins with `*`. For example for this tag:
`#AK_Step1_v12::#FirstAid::05_Pharm::02_Autonomic_Drugs::15_beta-blockers::*B-Antagonists::Cardioselective_B1_Antagonists`
the slug should be this:
`step1-fa-pharm-autonomic_drugs-beta-blockers`
Everything after the tag …

[BUILD-928] fix: Update `mh_tag_to_resource_title_and_slug`

---

ankihub/gui/reviewer.py

I added the `setUpdatesEnabled` (https://doc.qt.io/qt-6/qwidget.html#updatesEnabled-prop) call in order to try to reduce flickering of the sidebar webviews when switching to a new page.
However when the page takes long to load and you resize the sidebar using the slider, it leads to very odd liking visuals, the sidebar leaves some kind of traces on its old position.
This is why we should remove the `setUpdatesEnabled` calls.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-929
- Remove `setUpdatesEnabled` calls

[BUILD-929] fix: Remove `setUpdatesEnabled` calls

---

ankihub/gui/reviewer.py
ankihub/gui/web/templates.py

We need to prevent showing duplicate resources for a note.
If there are multiple tags that reference a resource, there should still be just one tab for the resource.
Here is a screenshot of the problem:
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-932
- Add the `_get_resources` function, which returns a list of resources without duplicates
https://github.com/AnkiHubSoftware/ankihub_addon/blob/117bfe33a6b0cf0237cf3f0df1b10dfb328ce9b9/ankihub/gui/reviewer.py#L519
- Use the `_get_resources` function for updating tabs and for updating the resource counts on the reviewer buttons
- You can add these tags to a note
```
AK_Step1_v12::#FirstAid::05_Pharm::02_Autonomic_Drugs::15_beta-blockers::*B-Antagonists::Cardioselective_B1_Antagonists::Basics …
```

[BUILD-932] fix: Don't show duplicate resource tabs

---

.github/workflows/ci.yml

Tests are currently hanging in the GHA:
https://github.com/AnkiHubSoftware/ankihub_addon/actions/runs/12411140318/job/34648205589
This PR fixes this by using an older ubuntu version for the tests runner.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-935
- Use `ubuntu-22.04` instead of `ubuntu-latest` (`ubuntu-24.04`)
- I don't know why, but the tests don't hang on `ubuntu-22.04`

[BUILD-935] chore: Fix tests hanging in GHA

---

ankihub/gui/reviewer.py
ankihub/gui/web/mh_no_urls_empty_state.html
ankihub/gui/web/reviewer_buttons.js
ankihub/gui/web/sidebar_tabs.html

https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-937
- [fix: Use correct font for empty state page](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1060/commits/dd5a83ee21b23b1e4dd1c61edf42c71ee65bc86e)
- Here is the design for the no-content page: https://www.figma.com/design/rWzQ7PPqAXf1piz5yTntaT/%F0%9F%91%91--Ankihub?node-id=8006-27532&t=F2Hz9n6TdGOZ6XWe-1
- [Don't set up sidebar if mh_integration flag is not active](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1060/commits/94c2dfdcd726f00d93a5e64375d54622ad4cb813)
- If you just have the `chatbot` feature flag and not the `mh_integration` feature flag, the reviewer buttons are still set up, this should not be the case
- <img …

[BUILD-937] fix: Reviewer UI fixes

---

ankihub/main/utils.py
tests/addon/test_unit.py

- [BUILD-940](https://ankihub.atlassian.net/browse/BUILD-940)
This PR updates the function `mh_tag_to_resource_title_and_slug` to use a new pattern to extract the slug from the tags
1. Access the reviewer with a note of the Anking deck
2. Check if the contents of the Boards & Beyond, and First Aid Forward are being loaded in the sidebar
To test this branch the reviewer needs to make a checkout to the ankihub repository on the branch `refactor/update-mh-scripts-to-new-slug-pattern`, and follow the steps described in this [PR](https://github.com/AnkiHubSoftware/ankihub/pull/2499)
[BUILD-940]: https://ankihub.atlassian.net/browse/BUILD-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-940] refactor: Refactor slug generation in mh_tag_to_resource_title_and_slug function

---

ankihub/gui/web/mh_no_urls_empty_state.html

- [BUILD-944](https://ankihub.atlassian.net/browse/BUILD-944)
This PR updates the style and the content of the empty state page when accessing the boards & beyond/first aid forward content
[BUILD-944]: https://ankihub.atlassian.net/browse/BUILD-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-944] refactor: Update empty stage page

---

ankihub/gui/errors.py

When there is a read timeout when communicating with AnkiHub, we are currently opening the error dialog.
We should handle this exception better by showing a non-disruptive message instead.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-964
Slack discussion: https://theanking.slack.com/archives/C07V3QBKZ2N/p1736354496219589?thread_ts=1736353994.016319&cid=C07V3QBKZ2N
User reports: https://community.ankihub.net/t/sync-bug-sync-01-07/374936
- Handle `requests.ReadTimeout` by showing message instead of error dialog

[BUILD-964] fix: Handle read timeout by showing message

---

ankihub/gui/menu.py

**Related issues**
- [BUILD-954](https://ankihub.atlassian.net/browse/BUILD-954)
**Proposed changes**
This pull request adds a new "Terms and Policy" submenu to the AnkiHub menu. The submenu includes links to the Terms and Conditions and Privacy Policy documents, which are accessible directly from the main menu.
The modifications include adding a new function `_ankihub_terms_and_policy_setup` in `menu.py`, which creates the terms and policy sub-menu with two actions: "Terms && Conditions" and "Privacy Policy". These actions are connected to open links to the respective documents on the AnkiHub community website.
**How to reproduce**
1. Run the AnkiHub application.
2. Access the main menu.
3. Click on the new "Terms and Policy" submenu.
4. Select either "Terms && Conditions" or "Privacy …

feat: Add terms and policy submenu to AnkiHub menu

---

ankihub/gui/menu.py
ankihub/settings.py
tests/addon/test_integration.py

- Refresh the AnkiHub menu when it's about to show
- This makes sure that the menu state is always correct
- Remove `Config.subscriptions_change_hook`, which became unnecessary now

fix: Refresh ankihub menu when about to show

---

ankihub/gui/menu.py
ankihub/private_config_migrations.py
ankihub/settings.py
tests/addon/test_integration.py

https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-973
The profile config keys used for the native integration were changed in https://github.com/ankitects/anki/pull/3232 before the PR was merged, and I forgot to update the keys in the add-on...
Log in to AnkiHub from the preferences screen and confirm the login is reflected in the add-on.

[BUILD-973] fix: Fix incorrect username/token profile keys being used

---

ankihub/ankihub_client/ankihub_client.py
ankihub/gui/overview.py
tests/addon/test_integration.py

https://ankihub.atlassian.net/browse/BUILD-921
This PR updates the flashcard selector button to show an upsell dialog if the user doesn't have access to the feature, with the same copy shown in the web app.
- Log in as a premium user.
- Open the flashcard selector and confirm no changes to existing behavior.
- Log in to a non-premium account.
- Open the flashcard selector and confirm the new upsell dialog is shown.
- Set/unset the `saw_trial_ended_message` field in the Django user model on the backend side and confirm the change in the title.
(emojis broken due to a font issue in my system)

[BUILD-921] Update smart search upsell

---

ankihub/gui/reviewer.py
ankihub/gui/web/reviewer_buttons.js
ankihub/gui/web/templates.py

We want the sidebar-related config options to immediately take effect when the config dialog is closed.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-982
- Refactor how button visibility is handled
- Update sidebar on config close
https://github.com/user-attachments/assets/e1f4aa6f-b928-4dd5-b006-7ebba81f4262

[BUILD-982] feat: Update sidebar immediately when config options change

---

ankihub/gui/config_dialog.py

Adjusts the copy of some config options according to this QA comment:
https://ankihub.atlassian.net/browse/BUILD-974?focusedCommentId=14259
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-985

[BUILD-985] fix: Adjust config options copy

---

ankihub/gui/menu.py

This fixes the AnkiHub menu missing on MacOS.  
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-989
QA comment: https://ankihub.atlassian.net/browse/BUILD-974?focusedCommentId=14224
- Add a place holder menu action so that the menu is not empty
- Since https://github.com/AnkiHubSoftware/ankihub_addon/commit/74ede28633794a3d083caa4ee869efdf9e2cdfc2 we are starting with an empty AnkiHub menu and set up the menu actions dynamically when the menu is clicked.
- Apparently MacOS doesn't show empty menus, which lead to the menu not showing up.
- Now we will have a placeholder menu action so that the menu is not empty.

[BUILD-989] fix: Missing AnkiHub menu on MacOS

---

ankihub/gui/reviewer.py

Users are getting errors when reviewing cards that have B&B/FA tags which don't follow the correct format for being used to show the resource information in the sidebar.
This task fixes the problem.
Sentry https://ankihub.sentry.io/issues/6236884494/?project=6546414&referrer=github-pr-bot
- Check whether the return value of `mh_tag_to_resource(tag)` is `None` before trying to access its `usmle_step` attribute

fix: `AttributeError` in `reviewer._get_resources`

---

ankihub/gui/reviewer.py

Currently we are making an request to fetch the premium status when the user enters the reviewer, even if it's not necessary. It's only necessary to fetch the premium status when any reviewer buttons are shown.
I noticed this when entering the reviewer for a non-AnkiHub deck and an AnkiHub login dialog showed up.
What happened is that the add-on made an request for the premium status, but the token was expired, so the login dialog was shown.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1007
- Only check premium status when any reviewer buttons are shown

[BUILD-1007] fix: Only check premium status in reviewer when necessary

---

ankihub/gui/editor.py

The `ankihub_id` field should be hidden in the editor, but it isn't, due to some change to Anki.
**With this PR**
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1016
https://forums.ankiweb.net/t/anki-24-11-addon-using-svelte-failing-with-cannot-require-svelte-internal/53068/6
- Use `setTimeout` instead of `require("svelte/internal").tick().then`

[BUILD-1016] fix: Hide ankihub_id field in editor

---

ankihub/gui/js_message_handling.py
tests/addon/test_integration.py

- [BUILD-1023](https://ankihub.atlassian.net/browse/BUILD-1023)
This PR updates the conditional of `GET_NOTE_SUSPENSION_STATES_PYCMD` on the `js_message_handling.py` module allowing sending the suspension state of the notes on the smart search dialog
1. Open the smart search dialog
2. Make a search
3. Use the state filter
4. Change the slider to and see if everything is working properly
[BUILD-1023]: https://ankihub.atlassian.net/browse/BUILD-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUILD-1023] fix: Fix state filter not working on smart search

---

ankihub/feature_flags.py
ankihub/gui/errors.py
ankihub/gui/reviewer.py
ankihub/settings.py
tests/client/test_client.py

Fixes an error users were occasionally getting in the reviewer when not logged in.
https://ankihub.sentry.io/issues/6253435393/events/f027550d1cb344b9ad9a5cb6b6c3aa9c/?project=6546414
Also makes some other improvements to the handling of 401 exceptions in the reviewer.
https://ankihub.sentry.io/issues/6253435393/events/f027550d1cb344b9ad9a5cb6b6c3aa9c/?project=6546414
https://community.ankihub.net/t/got-an-error-message/397521
The error was caused by our exception handler raising an exception while handling an 401 `AnkiHubHTTPError`.
The exception handler raised an exception because it was calling `config.save_token()`, which in turn called the callbacks in `config.token_change_hook`. 
One of the callbacks  (`update_feature_flags_in_background`) called `aqt.mw.taskman.run_in_background`. …

fix: Exception in exception handler, handling of 401 in reviewer

---

ankihub/lib/mashumaro/core/meta/helpers.py

This task fixes the add-on not working due to an update of the mashumaro library.
The PR re-applies a patch to the mashumaro library which was previously added in #351 and got removed when updating to mashumaro version 3.15 in #1097.
From the description of #351:
> This error was caused because the mashumaro (https://github.com/Fatal1ty/mashumaro) serialization library couldn't handle the module name of the add-on starting with a number. (Anki installs add-ons downloaded from AnkiWeb into directories named by their AnkiWeb id which consists of numbers).
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1062
- Apply a patch to mashumaro to make it handle module names starting with numbers
You can reproduce the `SyntaxError` by checking out the main …

[BUILD: 1062] fix: Mashumaro not handling module names with numbers

---

ankihub/gui/decks_dialog.py

Fix some issues reported during QA: https://ankihub.atlassian.net/browse/BUILD-1013:
- Update titles of selector dialogs.
- Update confirmation dialogs' "No" button label to "Cancel".
- Increase minimum height of Deck Management screen.
https://github.com/AnkiHubSoftware/ankihub_addon/pull/1090

fix: Update Note Type Management copies and fix space issue

---

ankihub/ankihub_client/ankihub_client.py
ankihub/gui/overview.py
ankihub/gui/reviewer.py
ankihub/gui/web/reviewer_buttons.js
tests/addon/test_integration.py

[BUILD-1048](https://ankihub.atlassian.net/browse/BUILD-1048)
[Webapp - PR](https://github.com/AnkiHubSoftware/ankihub/pull/2585)
Modify the `api/users/me` endpoint to check user's access to the _reviewer extension_ and _flashcard selector_ features. 
Remove `is_premium` and `is_trialing` fields as they don't define feature's access.
Add `has_reviewer_extension_access` and `has_flashcard_selector_access` fields to the user details
Refactor all code that involve `is_premium` and `is_trialing` 
1. Select any user with no access to the features (not trialing, premium or lifetime) - related webapp [branch](https://github.com/AnkiHubSoftware/ankihub/pull/2585)
2. Open the addon
3. Select any deck and click on the flashcard selector icon on the bottom left
4. A upsell dialog must appear
5. Open …

[BUILD-1048] Check features access instead of plan or trial

---

ankihub/ankihub_client/ankihub_client.py
ankihub/gui/decks_dialog.py
ankihub/gui/overview.py
ankihub/gui/reviewer.py
ankihub/gui/web/reviewer_buttons.js
tests/addon/test_integration.py

Reported during QA in https://ankihub.atlassian.net/browse/BUILD-1004
This fixes the fields selector dialog shown for the "Publish field" function not accepting input due to the wrong widget set as parent. This only happens on macOS.
Use the Publish Field button in Deck Management and select a note type with a new field.

fix: Fix fields dialog not accepting input on macOS

---

ankihub/gui/decks_dialog.py
ankihub/gui/utils.py

Fix more issues reported during QA of [BUILD-1013](https://ankihub.atlassian.net/browse/BUILD-1013):
- Update titles of confirmation dialogs.
- Revert to using default QDialogButtonBox button layout
-  Report note type creation errors (e.g. "A note type with this name already exists.")
[BUILD-1013]: https://ankihub.atlassian.net/browse/BUILD-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: UI fixes for note type creation

---

ankihub/gui/decks_dialog.py
ankihub/main/note_type_management.py

https://ankihub.atlassian.net/browse/BUILD-1013
This updates the UI to disable the buttons if they are not applicable, according to the Figma updates.
1. Go to the Deck Management screen.
2. Select a deck you own and notice the state of the buttons.
3. The "Publish note type" button should be disabled if you have no note types to upload to AnkiHub. This is unlikely because most of the time you'll have Anki's standard types there. But you can confirm this is working by deleting all non-AnkiHub types from _Tools > Mange Note Types_.
4. The "Publish field" button should be disabled if there are no new fields in any types associated with the deck. This button will probably show as disabled most of the time. You can confirm it's working by adding a new field to any relevant AnkiHub note type …

fix: Disable note type buttons if not applicable

---

ankihub/gui/decks_dialog.py
ankihub/gui/utils.py

Fix a few issues reported in QA of https://ankihub.atlassian.net/browse/BUILD-1020
- Make Cancel button work
-  Disable Proceed button if nothing is selected 
- Add a prompt for fields dialog instead of a title
- Add a new field to an AnkiHub note type
- Go to the Deck Management screen and click "Publish field".
- Notice the changes in the fields dialog.

fix: Fix some issues with field selector UI

---

ankihub/main/note_type_management.py
ankihub/main/utils.py
ankihub/settings.py
tests/addon/test_integration.py
tests/addon/test_unit.py

Fixes `ankihub.main.note_type_management.note_types_with_template_changes_for_deck`, by fixing the removal of note type modifications.
This fixes the issue where note types were available for selection in the "Publish style/template updates" flow after being published.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1025
- Combine code from `note_type_management.note_type_with_ankihub_end_comment_removed` and `main.utils.undo_template_modification` into `main.utils.note_type_without_template_and_style_modifications`
- Previously we were not removing all template modifications, which caused problems with the ""Publish style/template updates" flow
- `note_type_without_template_and_style_modifications` now removes all modifications from the …

fix+ref: note_types_with_template_changes_for_deck

---

ankihub/gui/decks_dialog.py
ankihub/main/note_type_management.py

When an user tries to publish updates to note styling and templates of a note type that had templates added/removed, this dialog should be shown:
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1090
- Add `note_type_had_templates_added_or_removed()` to `note_type_management.py`
- Use `note_type_had_templates_added_or_removed()` in `decks_dialog.py` when user selected note type to publish updates for, show message if templates were added or removed 
- Add/remove template of a note type which belongs to an AnkiHub deck you are the owner of
- Try to publish style and template updates for it
- The dialog should show up

[BUILD-1090] Disallow updating note type with added/removed templates

---

ankihub/ankihub_client/ankihub_client.py
ankihub/main/note_type_management.py
tests/addon/test_unit.py

The changes ensure that `note_type_management.add_note_type_fields`…
- assigns field ords correctly
- only updates new fields and field ordering, and not the attributes of existing fields
- handles the case when the Anki note type is missing some fields which exist on the AnkiHub note type
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1093
- Update `note_type_management.add_note_type_fields`
- Add tests

[BUILD-1093] Adjust add_note_type_fields

---

ankihub/entry_point.py
ankihub/gui/decks_dialog.py
ankihub/gui/errors.py
ankihub/gui/menu.py
ankihub/gui/operations/username.py
ankihub/main/deck_creation.py
ankihub/main/note_type_management.py
ankihub/main/utils.py
ankihub/settings.py
tests/addon/conftest.py
tests/addon/test_integration.py
tests/addon/test_unit.py
tests/client/cassettes/TestGetUserDetails.test_get_user_details.yaml
tests/client/test_client.py

https://ankihub.atlassian.net/browse/BUILD-1013
Because we clone chosen note types under new names, the old ones will still be shown next time, but we show an error message when they are chosen. This PR excludes any note types with duplicate names to reduce confusion.
- Publish any new note type.
- Click "Publish field" again and notice the previously chosen note type is no longer shown.

fix: Exclude note types with duplicate names from publication flow

---

ankihub/db/db.py
ankihub/main/importing.py
tests/addon/test_integration.py

https://ankihub.atlassian.net/browse/BUILD-1079
https://ankihub.atlassian.net/browse/BUILD-1078
After BUILD-1078, the web app can return notes with missing fields (indicating empty fields). This PR implements the necessary add-on changes to handle this correctly.
- Add a new field to an AnkiHub note type then publish the field from the Deck Management screen.
- Log in and sync with AnkiHub in a new Anki profile.
- Make any change to the new field in an existing note then sync again.
- Notice your changes are cleared after sync.
- Same process can be done with the Reset local changes option to confirm missing fields are cleared.

[BUILD-1079] Support importing notes with subset of fields

---

ankihub/ankihub_client/ankihub_client.py
ankihub/gui/errors.py
ankihub/gui/operations/ankihub_sync.py
tests/addon/test_integration.py
tests/client/test_client.py

This PR enhances the AnkiHub client to provide a more responsive user experience and better handling of server connectivity issues. It introduces separate connection/read timeouts and categorizes operations as standard or long-running to reduce UI freezing during network operations, particularly when the server is unreachable or under heavy load.
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1076
- Fetch deck subscriptions in background during sync to not freeze the UI
- [Update maintenance message](https://github.com/AnkiHubSoftware/ankihub_addon/commit/8c9ca395bbd211106ef16909ca859e6afc763b6b)
- Change client timeout and max retries logic
- Now the connection timeout is configured separately from the read timeout. We have a short connection …

[BUILD-1076] fix: Add on-freezes when server unreachable

---

ankihub/anki_logger.py
ankihub/entry_point.py
ankihub/gui/operations/ankihub_sync.py

We have some errors that are caused by `aqt.mw.col.db` being `None` during the AnkiHub sync:
- https://ankihub.sentry.io/issues/5392204953/?project=6546414&referrer=issue-stream&stream_index=0
- https://ankihub.sentry.io/issues/6417858275/?project=6546414&query=%27NoneType%27%20object%20has%20no%20attribute%20%27scalar%27&referrer=issue-stream&stream_index=0
When these happen during the auto sync when Anki is closing, the errors prevent Anki from closing.
This PR applies a fix to handle the case when `aqt.mw.col.db is None`, so that Anki is closed.
I don't know why `aqt.mw.col.db is None` sometimes during the sync, so this PR also adds some logs to get more information about this.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-87
- Don't do a custom …

[NRT-87] Handle `aqt.mw.col.db is None` during sync, add logs

---

ankihub/gui/webview.py

Fixes an issue reported here: https://ankihubllc.slack.com/archives/C08DWTDEDK8/p1742476753144639
> When I click on “Open in browser,” the browser window opens but always stays behind the Smart Search window, making it impossible to view the flashcards in the browser unless I close the Smart Search window.
- Make flashcard selector dialog non-modal
- This makes it possible to interact with the browser while the flashcard selector is open

fix: Make flashcard selector non-modal to allow interaction with browser

---

ankihub/ankihub_client/ankihub_client.py
ankihub/db/db.py
ankihub/db/db_migrations.py
ankihub/db/exceptions.py
ankihub/db/models.py
ankihub/gui/deck_updater.py
ankihub/gui/errors.py
ankihub/gui/operations/db_check/ah_db_check.py
ankihub/settings.py
tests/addon/test_unit.py

After adding new fields to note types via the “Publish fields” feature, some users are reporting that fields contents are in the wrong fields.
The cause of the issue is that we are storing the field values as one string with the field values joined by a delimiter. When a new field gets added to the note type, the field values are off.
Related web app PR: https://github.com/AnkiHubSoftware/ankihub/pull/2645
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-100
We will start storing the fields as a json dict in the AnkiHubDB. This way, when new fields are added to the note type, we will still be able to tell which field value belongs to which field.
Incorrect values in the DB will be corrected by setting a flag to download the full deck on the next sync …

[NRT-100] Store fields in json dict in AnkiHubDB, fix missing values

---

.envrc.dev
ankihub/gui/media_sync.py

During development its sometimes convenient to disable media downloads.
This PR adds an env var to disable them.
- Add mechanism to disable media downloads by setting the `DISABLE_MEDIA_DOWNLOADS` env var to `1`
- Add the env var to the `.envc.dev` file

chore: Allow to disable media download using env var

---

ankihub/config.json
ankihub/settings.py

This PR addresses the need to update the staging deck ID and make it configurable. Currently, the staging environment uses a hardcoded deck ID, which is used when the `use_staging` setting is set to `true`. This PR introduces a change to allow the `staging_anking_deck_id` to be configurable. If a `staging_anking_deck_id` is not provided in the config, it will fallback to a default UUID.
(If the `STAGING_ANKING_DECK_ID` env var is provided, it will take precedence.)
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-113
- [Add staging_anking_deck_id to config](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1136/commits/4ad957e0e4ddf271510cb6395b890e980941337f)
- [Update hardcoded staging anking deck …

[NRT-113] chore: Update staging deck id, make it configurable

---

ankihub/gui/reviewer.py
tests/addon/test_integration.py

https://ankihub.atlassian.net/browse/ACTV-28
The add-on's use of a separate QWebEnginePage for each sidebar button was causing pages to fail to load and crashes after doing a few reviews.
Steps to reproduce the issues without this PR:
1. Open the chatbot.
2. Do some reviews.
3. Switch to other sidebar buttons a few times. You should see the FirstAidForward page specifically sometimes fails to load. When that happens, and you switch to a different button, Anki will crash.
The crash happens inside the `AnkiWebView.setPage()` call in `ReviewerSidebar.set_content_url()`. This is probably a Qt bug.

[ACTV-28] Fix blank pages and crashes when switching sidebar buttons

---

ankihub/gui/webview.py

- Set allow_drops as true to allow drag and drop
In Anki Desktop:
- Open the Smart Search
- Click "Files" to search using file
From your file explorer:
- Drag a supported file into the file input area
- Make sure file appears in preview
- Make sure it shows upload confirmation
https://github.com/user-attachments/assets/5a1af6c9-bad7-4274-b5ce-d094bdae5d0b
[NRT-103]: https://ankihub.atlassian.net/browse/NRT-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NRT-103] Drag and drop for file selector in smart search doesn't work consistently

---

ankihub/gui/js_message_handling.py
ankihub/gui/webview.py

Related web app PR: https://github.com/AnkiHubSoftware/ankihub/pull/2655
This PR adds a `searchString` parameter to the `ankihub_open_browser` pycmd. This allows the web app to pass various search strings to the Anki browser.
It also fixes an issue with the theme of the smart search dialog being off from Anki's theme.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-95
- [Allow passing search string to OPEN_BROWSER_PYCMD](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1139/commits/6ed27c82d1b264852564b6b54a1c4a4466f76581)
- [Fix smart search page and dialog theme](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1139/commits/f08b58f74ca57ff83a135d5dd348e02ec8b27989)
- Checkout the web app PR: …

[NRT-95] Allow passing search string to ankihub_open_browser pycmd, fix smart search theme

---

ankihub/gui/addons.py
ankihub/gui/errors.py
ankihub/gui/utils.py
requirements/dev.txt
tests/addon/test_unit.py

https://ankihub.atlassian.net/browse/ACTV-51
This wraps TermsAndConditionsDialog.display() call possibly ran on startup with Anki's `aqt.mw.progress.single_shot()` utility function. This delays the execution of the call while ensuring it doesn't trigger while a progress dialog is shown, which commonly causes app freezes (especially on macOS it appears).
Unfortunately we've not found a reliable way to trigger the issue yet, but you can increase the possibility of it occurring by running Anki with an AnkiWeb account with autosync enabled and a lot of changes to sync.

[ACTV-51] Fix TermsAndConditionsDialog freezing on startup

---

ankihub/gui/reviewer.py
ankihub/gui/webview.py

https://ankihub.atlassian.net/browse/ACTV-56
This PR just sets a parent widget for `CustomWebPage` so it doesn't garbage collected, which was causing users to be logged out of AnkiHub in the sidebar (due to `AuthenticationRequestInterceptor` no longer running).
To reproduce the issue before this PR:
1. Open the sidebar and confirm you're logged in.
2. Close the sidebar, open [Anki's debug console](https://docs.ankiweb.net/misc.html#debug-console) and run `mw.garbage_collect_now()`.
3. Open the sidebar and notice you're prompted to log in.
4. Repeat the same steps after checking in this PR and confirm you're still logged in.
See video attached to JIRA issue.

[ACTV-56] Fix intermittent sidebar logout issue

---

.devcontainer/Dockerfile

This just adds the `libxcb-cursor-dev` package to the list of installed packages in the dev container as it appears to be required in recent Anki versions.
I was getting this error while trying to run Anki in GitHub Codespaces:
```
xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin
```
Installing `libxcb-cursor-dev` fixed the issue and made Anki run normally.
You can confirm that by running this PR in a new codespace.

chore: Install the `libxcb-cursor-dev` package in dev container

---

ankihub/gui/operations/db_check/ah_db_check.py

This PR fixes a `NoneTypeError` in the `ah_db_check.py` file.
Sentry: https://ankihub.sentry.io/issues/5375216652/?project=6546414&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=freq&stream_index=6
https://ankihub.atlassian.net/jira/software/c/projects/BUILD/boards/1?selectedIssue=BUILD-1102
- Check if the deck is in the private config before trying to set a config setting to avoid the `NoneTypeError`

[NRT-153] fix: NoneTypeError in ah_db_check.py

---

tests/client/test_client.py

This PR fixes client tests on CI by waiting for the server to become responsive before running a test.

Fix client tests on CI

---

ankihub/gui/browser/browser.py
ankihub/gui/config_dialog.py
ankihub/gui/flashcard_selector_dialog.py
ankihub/gui/overview.py

This fixes the issue found during QA for the new smart search buttons: https://ankihub.atlassian.net/browse/NRT-145?focusedCommentId=19899
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-172
- [Update config dialog section label](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1147/commits/5527e7ee0caf41adcd72a5804bdac70e97dee738)
- [Fix button frame showing on MacOS](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1147/commits/4e31a967bdf977413302135e543c53ead93dad34)
- [Add margin to browser button on mac](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1147/commits/67a03f8a80b73511403e876a78ede889d38ee7be)
- [Fix error because of deleted dialog](https://github.com/AnkiHubSoftware/ankihub_addon/pull/1147/commits/31b5501eb882b0ea340 …

[NRT-172] Fix issues with new smart search buttons

---

ankihub/gui/browser/browser.py

We forgot to add a feature flag check when adding the smart search button to the browser sidebar. This PR adds the feature flag check.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-181
- Add the feature flag check
- It uses the same feature flag as for showing the smart search button in the deck overview:
https://github.com/AnkiHubSoftware/ankihub_addon/blob/b9128cff321bde6b2b44652c19e46803611fdce1/ankihub/gui/overview.py#L68

[NRT-181] Only show smart search button in browser if feature flag is enabled

---

ankihub/gui/errors.py
ankihub/gui/menu.py

https://ankihub.atlassian.net/browse/ACTV-95
This fixes the Upload Logs functions getting stuck on the progress dialog if an exception is thrown.
To reproduce the freeze issue _before_ this PR:
1. Disconnect from the internet.
2. Use _AnkiHub > Help > Upload logs_ and notice it's stuck forever.
After this PR you should immediately see an error dialog instead.

[ACTV-95] Fix Upload Logs getting stuck in case of errors

---

tests/addon/test_unit.py

Fixes the hanging `TestUploadLogs::test_with_exception` test by mocking a dialog.

chore: Fix hanging test upload logs test

---

ankihub/main/importing.py
ankihub/main/utils.py
tests/addon/test_integration.py
tests/addon/test_unit.py
tests/fixtures.py

Refine the logic in `AnkiHubImporter`  so that it auto-selects the correct existing AnKing deck more often.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-185
- Update `AnkiHubImporter._cleanup_first_time_deck_import` to merge the newly created AnKing deck into an existing deck if it:
- has "anking" in its name (case-insensitive)
- had 1000+ AnKing cards in it
- is the only such deck
- Refactor code for finding existing deck for other decks (non-AnKing)
- Previously `AnkiHubImporter.import_notes()`  returned the dids the notes were imported into. Now `import_notes()` returns `None` and we are querying for the deck ids in `_get_existing_regular_deck_id()`
- Unsubscribe from AnKing deck
- Make sure the AnKing deck in the Anki collection has "anking" …

[NRT-185] Improve logic for identifying previously existing decks during import

---

ankihub/gui/messages/templates/deck_import_summary.html
ankihub/gui/operations/deck_installation.py
ankihub/gui/utils.py
ankihub/main/importing.py
tests/addon/test_unit.py
tests/factories.py

The 'Import Summary' dialog has been significantly updated to provide much more detailed and context-specific information to users after importing decks.
The scenarios are described in the table in the Jira issue description: https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-212
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-212
* **Enhanced User Feedback**: The 'Import Summary' dialog has been significantly updated to provide much more detailed and context-specific information to users after importing decks, moving beyond generic success messages.
* **Categorized Deck Import Results**: Imported decks are now intelligently categorized into newly created, merged with existing decks (same name), or merged with …

[NRT-212] Update the Import Summary dialog

---

ankihub/gui/messages/templates/deck_import_summary.html
tests/addon/test_unit.py

Adjustment to the Deck Import Summary dialog, specifically to the warning about skipped notes.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-229
- Move the skipped-notes warning before the AnkiWeb warning
- Adjust copy
You can run these scripts in Anki's debug console to show the dialog.
```python
import uuid
import ankihub
ankihub_deck_names = ["Pathology Deck"]
anki_deck_names   = ["Pathology Deck"]
import_result = ankihub.main.importing.AnkiHubImportResult(
ankihub_did=uuid.uuid4(),
anki_did=1,
updated_nids=[],
created_nids=[1, 2],
deleted_nids=[],
marked_as_deleted_nids=[],
skipped_nids=[100, 101, 102, 103, 104],
first_import_of_deck=True,
merged_with_existing_deck=False,
)
ankihub.gui.operations.deck_installation._show_deck_import_summary_dialo …
```

[NRT-229] Update skipped-notes warning on Deck Import Summary dialog

---

ankihub/gui/decks_dialog.py
ankihub/gui/operations/subdecks.py
ankihub/gui/utils.py
ankihub/main/utils.py
tests/addon/test_integration.py

Enable users to move cards directly from the Deck Management dialog when they change the destination deck.
When the user changes the destination deck, if the original deck contains notes, a new pop-up will trigger to move the cards or skip this suggestion.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-213
* **Enhanced Deck Management**: When a user changes the destination deck for an AnkiHub deck, the system now detects if there are cards outside this deck, which should potentially get moved to the new destination deck.
* **User Prompt for Card Movement**: If cards are found outside the new destination deck, a new pop-up dialog is triggered, asking the user if they wish to move these existing cards to the newly selected destination deck.
* **Card …

[NRT-213] Enable users to move cards when changing destination deck

---

ankihub/gui/reviewer.py

https://ankihub.atlassian.net/browse/ACTV-123
This adds `AnkiWebView.set_open_links_externally(False)` calls after each `AnkiWebView.setHtml()` call to fix the issue. `setHtml()` internally calls `self.set_open_links_externally(True)`, so this is needed.
To reproduce the issue before this PR, open the AnKing deck and switch between the sidebar buttons. You should see that the sidebar buttons open the web page in an external browser.
Interestingly, the issue doesn’t seem to appear in my dev environment. I had to install the add-on from AnkiWeb to a separate profile and test there. I'm not sure why this is the case.

[ACTV-123] Fix chatbot open in external browser

---

ankihub/gui/decks_dialog.py

Adjust the dialog for moving cards when changing the destination deck according to QA feedback.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-244
- Change the copy of the “Skip” button to “Don’t Move.”
- Add a “Cancel” button 
- So the buttons will be Cancel / Don’t Move / Move 
- When the user presses "Cancel”, it will return to the previous dialog (Select destination for new cards)
- The dialog is now also shown when changing the destination deck to the current one, making it easier to move all cards to it, it that's what the user wants
- Install a deck
- Set up an (empty) Anki deck
- Open the Deck Management dialog, and change the Destination for New Cards to the empty deck
- Choose "Move Cards"
- The cards should be moved to the selected deck

[NRT-244] Adjust dialog for moving cards when changing destination deck

---

ankihub/gui/browser/browser.py
ankihub/gui/webview.py
tests/addon/test_integration.py

This pull request introduces a significant new feature, allowing users to launch an AI chatbot directly from the Anki browser for selected AnkiHub notes. It includes the necessary UI additions, such as a context menu entry and global keyboard shortcuts, and also involves a substantial refactoring of the context menu management system to improve maintainability and extensibility for future features. Additionally, the underlying webview component has been made more configurable.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-238
* **New Feature: AI Chatbot Integration**: I've added a new 'AI Chatbot' option to the browser's context menu. This allows users to launch a dedicated chatbot interface directly from the Anki browser when a single AnkiHub note …

[NRT-238] Allow users to launch chatbot from browser

---

.pre-commit-config.yaml
ankihub/gui/browser/browser.py
ankihub/gui/flashcard_selector_dialog.py
ankihub/gui/webview.py
tests/addon/test_integration.py

Fixes some issues with the chatbot dialog you can open from the browser.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-250
* **AI Chatbot Availability**: The 'AI Chatbot' context menu option in the browser is now only enabled if exactly one AnkiHub note is selected AND the related AnkiHub deck has note embeddings. A new helper function `_related_ah_deck_has_note_embeddings` was introduced to facilitate this check.
* **Generalized Dialog Display**: The `AnkiHubWebViewDialog.display` method was refactored to accept a `Qt.WindowModality` argument, making the dialog display behavior more flexible and standard across different dialogs, replacing the specific `use_open` flag.
- Using `Qt.WindowModality.ApplicationModal` fixes an issue where the dialog …

[NRT-250] Adjust chatbot dialog

---

ankihub/gui/editor.py

https://community.ankihub.net/t/multiple-error-messages-come-out-of-nowhere-while-annotating-anki-cards/523844/
Old add_cards_did_add_note hooks are not cleaned up if open_suggestion_dialog_for_single_suggestion() throws an exception. This is a quick fix for the issue (Sentry shows quite a few reports).

fix: Guard against suggestion errors if editor is deleted

---

ankihub/main/block_exam_subdecks.py
ankihub/main/subdecks.py
ankihub/main/utils.py
tests/addon/test_integration.py
tests/addon/test_unit.py

This pull request addresses a critical bug where notes were inadvertently deleted when a subdeck containing further subdecks was removed. The issue stemmed from an incomplete method of identifying all notes associated with a deck hierarchy. The changes introduce a robust utility function to correctly gather all note IDs within a deck's hierarchy and integrate this function into the existing subdeck handling and deck flattening logic, thereby preventing data loss and improving the overall integrity of deck operations.
https://ankihub.atlassian.net/jira/software/c/projects/NRT/boards/41?selectedIssue=NRT-403
* **Introduction of `note_ids_in_deck_hierarchy`**: A new utility function `note_ids_in_deck_hierarchy` has been added to `ankihub/main/utils.py`. This function is designed to …

[NRT-403] Fix notes getting deleted when deleting subdeck that has subdeck
